### ISSUE TITLE
没有dockerfile ？

### ISSUE THREAD

**Issue by zcsk18** [SuLingGG/OpenWrt-Rpi-Docker#2]
为啥没有dockerfile 呢？

**Comment by SuLingGG** [comment]
因为这个项目是先通过 Github Action 编译出 tar.gz 格式的 rootfs 文件，然后再把 rootfs 通过 docker import 导入进容器，最后再将最后的容器状态 docker commit 出来的，所以没用到 Dockerfile。
当然通过 Dockerfile 来做也是可以的，但是过程其实换汤不换药（虽然更优雅一些
