### ISSUE TITLE
树莓派4的 Debian-Pi-Aarch64 桌面全功能版最新固件 拉取rpi2和rpi4都不行

### ISSUE THREAD

**Issue by Flammulinavelutipes** [SuLingGG/OpenWrt-Rpi-Docker#21]
root@raspbian:/home/pi# docker run --restart always --name openwrt -d --network macnet --privileged registry.cn-shanghai.aliyuncs.com/suling/openwrt:rpi2 /sbin/init

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

f47a3a1df69305ff05829d79deefe3f4b43ac6ac0f30e849af2ca092fafc0ab5

**Comment by SuLingGG** [comment]
这是比较新的 docker 程序另外加的一个验证。我这里解释起来很麻烦，忽略这个提示即可，执行完这条命令之后容器已经在运行了，接着做下面的步骤就行。
