### ISSUE TITLE
无法访问openwrt管理界面

### ISSUE THREAD

**Issue by becomecore** [SuLingGG/OpenWrt-Rpi-Docker#3]
按照https://mlapp.cn/376.html的教程，做到

/etc/init.d/network restart
--

之后，无法进入openwrt控制面板。

在路由器中已经可以看到指定的ip（树莓派是192.168.1.100，指定的ip为192.168.1.101)
且显示mac地址与树莓派不同，mac为 02 42 c0 a8 01 02

在树莓派浏览器中输入192.168.1.101，提示：
无法访问 http://192.168.1.101/
ERR_ADDRESS_UNREACHABLE

**Comment by SuLingGG** [comment]
这个问题可能会在极少数情况下在一些固件上出现，但是我自己没有遇到过...
最近重做了配置，似乎解决了这个问题。
可以试试最新版的 Docker 镜像。

**Comment by long2ice** [comment]
我这边也遇到了这个问题，请问是怎么解决的呢
