### ISSUE TITLE
op的 passwall 不生效

### ISSUE THREAD

**Issue by matthuo333** [SuLingGG/OpenWrt-Rpi-Docker#4]
国内站点可以访问，但是出海不行，所有VPS可用性检测均失败。

基于Libreelec 的插件库安装docker。

**Comment by SuLingGG** [comment]
这个问题群里之前也有人反映过...
Libreelec 似乎确实没办法在 Docker 里运行 OpenWrt。

**Comment by matthuo333** [comment]
> 这个问题群里之前也有人反映过...
> 
> Libreelec 似乎确实没办法在 Docker 里运行 OpenWrt。

op可以运行，但是那些代理工具貌似不行

**Comment by matthuo333** [comment]
那x86平台跑哪个虚拟环境可以完整运行op呢？

**Comment by SuLingGG** [comment]
> 那 x86 平台跑哪个虚拟环境可以完整运行 op 呢？

完整运行的话，只要是虚拟机都可以。

如果是桌面平台的话，可以试试 VirtualBox 或者 VmWare，
NAS 平台的话，群晖或者 UnRaid 都自带虚拟机套件，
或者直接使用虚拟机平台，例如 Exsi 或者 PVE 。

以上都可以在虚拟机中完整运行 OpenWrt 环境。
