### ISSUE TITLE
树莓派4 libreelec docker 211 exec format error

### ISSUE THREAD

**Issue by wangfs763** [SuLingGG/OpenWrt-Rpi-Docker#6]
作者你好，请教一个问题。我在树莓派4安装了 libreelec，安装了 docker 插件。不管是使用你的镜像，还是导入自己编译的 rootfs 文件，运行时一直报 211 异常， exec format error。看 issues 中有个树莓派3有同样异常，不知作者如何处理的？谢谢。

**Comment by wangfs763** [comment]
编译的镜像和拉取的镜像，目前似乎只能在 Debian pi os 上正常运行，其它系统无法使用。

**Comment by SuLingGG** [comment]
你好，根据你上面提供的内容，对于树莓派4，官网的 LibreELEC  应该为 armhf (32位) 固件，你可以尝试用 rpi2 标签拉取 32 位镜像，不出意外可以在 LibreELEC 上运行。

**Comment by wangfs763** [comment]
作者太坏了，又给打开了，“害”我还得测试一下。不过确实如此，对于libreelec，rpi2的镜像可以使用。多谢提醒！

**Comment by SuLingGG** [comment]
> 作者太坏了，又给打开了，“害” 我还得测试一下。不过确实如此，对于 libreelec，rpi2 的镜像可以使用。多谢提醒！

能用就行哈哈哈~😝😝
