### ISSUE TITLE
树莓派4上面报错

### ISSUE THREAD

**Issue by elarkasi** [SuLingGG/OpenWrt-Rpi-Docker#9]
**Linux raspi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux**

```
docker run --restart unless-stopped --network macnet --privileged --name openwrt sulinggg/openwrt:rpi4 /sbin/init
```

> standard_init_linux.go:211: exec user process caused "exec format `error"

**Comment by elarkasi** [comment]
btw, 跑 sulinggg/openwrt:latest 就没有问题

**Comment by SuLingGG** [comment]
请查看其他 Issues。

**Comment by elarkasi** [comment]
好的，谢谢
